### ISSUE TITLE
Suggestion: Warn about unchecked `DataTransactionResult`s (Sponge)

### ISSUE THREAD

**Issue by Limeth** [minecraft-dev/MinecraftDev#112]
Sponge plugin developers very often come across the need to use the Data API to assign values to `DataHolder`s such as `ItemStack`s. Often, it is easy to forget about the result of the action, specifically `DataTransactionResult`.

It would be great if MinecraftDev automatically highlighted all calls to `CompositeValueStore` methods which return a `DataTransactionResult` as warnings, if the result hasn't been used in further code.

Highlighted:
```java
ItemStack itemStack = ItemStack.of(ItemTypes.STICK, 1);
itemStack.offer(Keys.ITEM_DURABILITY, durability);
//        ^^^^^ warning: unchecked result
```

Proper usage:
```java
ItemStack itemStack = ItemStack.of(ItemTypes.STICK, 1);
DataTransactionResult result = itemStack.offer(Keys.ITEM_DURABILITY, durability);

if(!result.isSuccessful())
    throw new IllegalStateException("It's the apocalypse!");
```

**Comment by kashike** [comment]
I'd personally find this annoying.

**Comment by Minecrell** [comment]
@kashike You can turn off all inspections so I don't think that should be a big problem. Could also make it disabled by default if necessary.

**Comment by DemonWav** [comment]
This is a more complex check, so if it happens it might take a while.
