### ISSUE TITLE
Allow to disable automatically run setupDecompWorkspace or add an option to setup proxy when creating project

### ISSUE THREAD

**Issue by h404bi** [minecraft-dev/MinecraftDev#113]
> For `Forge` and `LiteLoader` projects this may take a considerable amount of time, as the automatic project creator will run `./gradlew setupDecompWorkspace` for you, which can take a lot of time, especially if you haven’t ran it before.

automatically run `./gradlew setupDecompWorkspace` is convenient for most users. but due to some network issue in some areas, some users (such as me) need to use proxy to run gradle, the task will be stuck if it automatically run without proxy setting.

So I open this issue to ask if can allow to disable automatically run the task, or provide an option to setup proxy for gradle when creating project (latter is better).

```
# socks
./gradlew setupDecompWorkspace -DsocksProxyHost=<host> -DsocksProxyPort=<port>
# https
./gradlew setupDecompWorkspace -Dhttps.proxyHost=<host> -Dhttps.proxyPort=<port>
# http
./gradlew setupDecompWorkspace -Dhttp.proxyHost=<host> -Dhttp.proxyPort=<port>
```

thanks! :100:

**Comment by Mumfrey** [comment]
It sounds like this is an [XY Problem](http://meta.stackexchange.com/questions/66377/what-is-the-xy-problem). Why are you not just setting those JVM arguments as `systemProp` in your user's `gradle.properties` which will just set the proxy globally for gradle on your system?

**Comment by h404bi** [comment]
@Mumfrey thanks for replying. global `gradle.properties` settings means all the gradle projects will use the proxy, including those projects no need to use that. But yeah, it sounds like this is an XY Problem. I will consider to use global `gradle.properties`...
