### ISSUE TITLE
Add warning when defining ResourceLocation which doesn't exist

### ISSUE THREAD

**Issue by killjoy1221** [minecraft-dev/MinecraftDev#126]
It should help to catch typos in the path. Should also be suppressible.

**Comment by Zidane** [comment]
@killjoy1221 

I don't think this will work out as some custom IResourcePack could provide resources from really anywhere....

**Comment by Mumfrey** [comment]
> I don't think this will work out as some custom IResourcePack could provide resources from really anywhere....

Including synthesising them. ResourceLocations are inherently a runtime thing and determining whether they are extant is not really a job for the IDE.

**Comment by DemonWav** [comment]
Closed due to the reasons described above.
