### ISSUE TITLE
2017.1 EAP - Installs wrong version

### ISSUE THREAD

**Issue by Meronat** [minecraft-dev/MinecraftDev#130]
I had problems using this plugin on the EAP but I think the problem is actually what version in installed.

Installing this plugin on the latest EAP for some reason installs version alpha-0.3.0 which came before a lot of the changes for 2016.3 and in general is just very outdated so I am thinking that is causing the incompatibilities.

**Comment by DemonWav** [comment]
That would make a lot of sense. I saw the issue someone showed earlier and I thought I had already fixed it. I'll get a 2017.1 build up tonight.

**Comment by DemonWav** [comment]
I'll also delete all of those old builds so that can't happen again. :)

**Comment by DemonWav** [comment]
Build has been uploaded.
