### ISSUE TITLE
Add copy Mixin target to clipboard action

### ISSUE THREAD

**Issue by DemonWav** [minecraft-dev/MinecraftDev#131]
Very similar to what's already in place for the `Find SRG Name` action, but with the MCP name, and the full signature.

This would apply to classes, fields, and methods.

**Comment by Minecrell** [comment]
https://github.com/minecraft-dev/MinecraftDev/pull/114, included in https://github.com/minecraft-dev/MinecraftDev/pull/125. Does not include classes but should be easy to add.

**Comment by DemonWav** [comment]
Oh, awesome!
