### ISSUE TITLE
Validate field opcode for @At references to field usages

### ISSUE THREAD

**Issue by stephan-gh** [minecraft-dev/MinecraftDev#136]
Related TODO comments: https://github.com/minecraft-dev/MinecraftDev/blob/5f9027b7c5013deb5abe103fa9207f75ca801301/src/main/kotlin/com/demonwav/mcdev/platform/mixin/inspection/signature/InjectorType.kt#L122-L130

**Comment by Mumfrey** [comment]
For the record omitting opcode is perfectly legal, it just causes the injector to match all field opcodes.
