### ISSUE TITLE
Accessor mixins should be excluded from class reference errors

### ISSUE THREAD

**Issue by killjoy1221** [minecraft-dev/MinecraftDev#141]
Accessor mixins are an exception to the rule

```java
@Mixin(GuiIngame.class)
public interface IGuiIngame {
    @Accessor
    void setPersistantChatGui(GuiNewChat chat);
}
```

This class should be accessible outside of the mixin package as well as any static methods declared.

**Comment by Mumfrey** [comment]
-> https://github.com/minecraft-dev/MinecraftDev/pull/125#discussion_r95822923

**Comment by liach** [comment]
Is this really resolved? In https://github.com/SpongePowered/SpongeCommon/pull/1214, I used an accessor mixin, but the same error shows up.

**Comment by DemonWav** [comment]
What version of the plugin are you using?

**Comment by liach** [comment]
v. 2016.3-0.5.5

**Comment by DemonWav** [comment]
Ah, I pulled your changes and gave it a look. I see the error. I'll see if I can figure out what's going on.

**Comment by liach** [comment]
Thanks for taking a look.

**Comment by DemonWav** [comment]
Ah, found the problem. Typo by @Minecrell :)

**Comment by DemonWav** [comment]
Version 2016.3-0.5.6 is be released now, should be fixed.

**Comment by Minecrell** [comment]
🎉
