### ISSUE TITLE
Exclude mixins from checking if Entity has World constructor

### ISSUE THREAD

**Issue by Barteks2x** [minecraft-dev/MinecraftDev#142]
With the following example mixin:

```java
@Mixin(EntityPlayerSP.class)
public class MixinEntityPlayerSP extends AbstractClientPlayer {

    public MixinEntityPlayerSP(World worldIn, GameProfile playerProfile) {
        super(worldIn, playerProfile);
    }
}
```

This is not a real entity so World constructor isn't needed here.

**Comment by DemonWav** [comment]
Ugh, @Mumfrey you cause me so many problems.

**Comment by Mumfrey** [comment]
> Ugh, @Mumfrey you cause me so many problems.

I literally exist just to make your life difficult.
