### ISSUE TITLE
Show error/warning when trying to create inner class in mixin class

### ISSUE THREAD

**Issue by Barteks2x** [minecraft-dev/MinecraftDev#150]
This is never correct, and when not expecting the inner class to be there (for example because it's overwrite of method that uses crash report) it leads to really hard to track down NoClassDefFoundError.

**Comment by Mumfrey** [comment]
You can create static inner classes in mixins as long as they are also mixins.

**Comment by Barteks2x** [comment]
Good to know that. 

But anonymous classes won't work, and this was what my inistal issue was - it was a very confusing issue to debug because it said it faiiled to load the Mixin<Something> class itself instead of Mixin<Somethign>$1, and that class wasn't ever referenced anywhere.

**Comment by Mumfrey** [comment]
Only synthetic inner classes are allowed in mixins, eg. switch tables.

**Comment by Barteks2x** [comment]
Overwrites of methods that contain small inner classes in larger mixins can be hard to find

**Comment by Mumfrey** [comment]
In eclipse, anonymous classes show up in the "outline" view of the class, I'm sure IntelliJ has something similar.

**Comment by Barteks2x** [comment]
I just wasn't expecting any inner classes there, so I didn't even think to look at that.
