### ISSUE TITLE
@At 'target' autocompletion doesn't handle inner classes

### ISSUE THREAD

**Issue by Aaron1011** [minecraft-dev/MinecraftDev#164]
When autocompleting a method call signature in the 'target' field of an `@At` annotation, inner classes are improperly separated from their parent by a slash (`/`) instead of a dollar sign (`$`)

For example, open SpongeForge's [MixinPlayerInteractionManager#onForgeCallLeftClickBlock](https://github.com/SpongePowered/SpongeForge/blob/76af398/src/main/java/org/spongepowered/mod/mixin/core/server/management/MixinPlayerInteractionManager.java#L238) with MinecraftDev installed. The plugin will show the current signature (which correctly uses a `$`) as incorrect. Clearing the `target` field and auto-completing `onLeftClickBlock` will cause MinecraftDev to insert an incorrect method signature, causing a mixin errror at runtime.

**Comment by Minecrell** [comment]
Thanks, this is already fixed in https://github.com/minecraft-dev/MinecraftDev/commit/5bc858cad09e962b3ba9882173555f8c7117978f
