### ISSUE TITLE
No forge 1.7.10 support

### ISSUE THREAD

**Issue by MrManiacc** [minecraft-dev/MinecraftDev#165]
Could you add forge 1.7.10 support please, thank you.

**Comment by DemonWav** [comment]
No.

**Comment by Kugelx** [comment]
Why?

**Comment by Kugelx** [comment]
1.7.10 is a very important modding version

**Comment by DemonWav** [comment]
#76 contains a bit of discussion for the reasoning. To expound on it a little, the tooling for Forge below 1.8 is different, and some of the API's as well, which wouldn't work with what Minecraft Dev is built to support currently. That's the technical reason, but there's also the idealogical reasoning of I don't want to encourage usage of these older Minecraft versions. The Minecraft community has a lot of inertia which makes it hard to move on from older versions, and I don't want to contribute to that problem.

**Comment by Kugelx** [comment]
Ok
