### ISSUE TITLE
Wrong detection of MCP AT file

### ISSUE THREAD

**Issue by Katrix-** [minecraft-dev/MinecraftDev#172]
MinecraftDev will label anything with a .cfg file ending as a MCP AT file, even if MCP isn't actually loaded itself.

Kind of surprised that no one caught this for so long.

**Comment by Minecrell** [comment]
I can't reproduce this in the latest version. You may still have an old file pattern registered in your configuration. Open Settings -> Editor -> File Types and check the registered patterns for `Access Transformers`. Remove `*.cfg` if it exists.
