### ISSUE TITLE
SpongeAPI 6 not detected

### ISSUE THREAD

**Issue by Katrix-** [minecraft-dev/MinecraftDev#180]
Unsure if this is an issue with SBT or not (don't think so as it should just look at the dependecies). 

I have a project with 4 subprojects. One shared, and one for 4.1.0, one for 5.0.0, and one for the snapshot branch of 6.0.0. The first three projects are recognized, but not the last one, despite the fact that it uses the SpongeAPI, is not.

**Comment by DemonWav** [comment]
I noticed this yesterday as well. [Definitely due to this change.](https://github.com/SpongePowered/SpongeAPI/commit/e1083729dda8508662a5913f88443e9c52153848) Before I merged it I thought I was handling that properly, but I must not be.
