### ISSUE TITLE
Can't see SRG names

### ISSUE THREAD

**Issue by Katrix-** [minecraft-dev/MinecraftDev#181]
Unsure if this is just be, but I can't get any SRG names when I right click stuff which clearly should have mappings. I can still look up the mappings in the gradle cache manually, so they still exist.

**Comment by DemonWav** [comment]
I can't reproduce, have you tried refreshing the Gradle project? Library detection no longer goes through Gradle, but we have to make calls to ForgeGradle to find the location of the mappings, so we still go through Gradle for that.

**Comment by Katrix-** [comment]
Yep, tried clean, cleanCache, refresh, and so on. The project is still detected as a Forge project, I just can't get the SRG names.

Forge version is 12.18.3.2185
Mappings are snapshot_20161116

**Comment by Barteks2x** [comment]
I think I also might have this issue but I'm not on my computer right now and I'm not 100% sure. I will check it tomorrow.

**Comment by DemonWav** [comment]
And you can confirm it's detected as an MCP project as well? `File -> Project Structure -> Facets` should be able to tell you.

**Comment by Katrix-** [comment]
Nope, not detected. The only project I have lying around that was detected is SpongeForge, but even there it didn't work. Is there any gradle command that I can run to see where it's saying that the SRG files are?

**Comment by Barteks2x** [comment]
Also not detected as MCP project here. it detects forge and mixin (it is a forge mod), but not MCP. I tried to manually select MCP but it didn't do anything.

**Comment by DemonWav** [comment]
Hmm, I know the issue now, but not the issue with MCP not being auto-detected, that's a different issue entirely. I'll fix the first issue and try and figure out what's causing the second.
