### ISSUE TITLE
Can't select different versions of a Class while debugging

### ISSUE THREAD

**Issue by gabizou** [minecraft-dev/MinecraftDev#195]
When debugging SpongeForge, and a step through passes through to a forge modified class, the debugger will remain "stuck" in SpongeCommon's dependency of the decompiled source, which clearly will not always match line numbers, nor will it match instructions compared to bytecode. This is pretty easy to demonstrate: 

1) Setup a Sponge Workspace,
2) Put a breakpoint [here](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/world/MixinExplosion.java#L389)
3) Step *into* [here](https://github.com/SpongePowered/SpongeForge/blob/bleeding/src/main/java/org/spongepowered/mod/mixin/core/common/MixinSpongeImplHooks.java#L279)
4) Move 1 more step, and watch how the `Block` class selected is "stuck" to the vanilla minecraft server source.

**Comment by Minecrell** [comment]
I'll take a look but it sounds unrelated to MCDev. We only handle the debugger position within Mixin classes, all other classes are ignored.

**Comment by DemonWav** [comment]
I thought that too, but I'm not sure if some code in the plugin is accidentally affecting this.
