### ISSUE TITLE
intellij throws an error when opening it creating a project

### ISSUE THREAD

**Issue by TheDomoKun** [minecraft-dev/MinecraftDev#1966]
### Minecraft Development for IntelliJ plugin version

2022.1-1.6.1

### IntelliJ version

Ultimate 2022.1.2

### Operating System

Windows 10 ltsc x64 

### Target platform

Bukkit, Spigot, Paper, Sponge, Architectury, Minecraft Forge, Fabric, Velocity, Mixins, BungeeCord, Waterfall

### Description of the bug

intellij throws this error when opening a project creation window:

 java.lang.ClassCastException: class com.intellij.util.ui.AsyncProcessIcon cannot be cast to class kotlin.jvm.functions.Function0 (com.intellij.util.ui.AsyncProcessIcon and kotlin .jvm.functions.Function0 are in unnamed module of loader com.intellij.util.lang.PathClassLoader @7d417077)

This started happening after I reset intellij to default settings

**Comment by Lucas104-alt** [comment]
You use Kotlin. Use Java Is Better From Plugins

**Comment by TheDomoKun** [comment]
how can i disable kotlin?

**Comment by Lucas104-alt** [comment]
I recomender Copy The Code And Past From New Project For Java And You Use Java But you have the Kotlin compiler

**Comment by TheDomoKun** [comment]
this does not work

**Comment by KaKusaOAO** [comment]
Same issue here. When I try to create a new project with the plugin enabled, it throws that exception.
It becomes a serious issue because I need to start a new Minecraft mod project like right now.

**Comment by RedNesto** [comment]
I was able to reproduce this issue in 2022.1.4, and doesn't appear to affect newer major versions (?)

Not sure how exactly the binary compatibility was broken here.

**Comment by DenWav** [comment]
I think a83d58a696f23a6c005fce36b10451c971d700aa fixes this issue.
