### ISSUE TITLE
git(hub) intergration 

### ISSUE THREAD

**Issue by loordgek** [minecraft-dev/MinecraftDev#200]
when i create a mc project(in my case forge project) i would like to also create a github repo for it

**Comment by DemonWav** [comment]
IntelliJ's Github integration already allows this, and the `.ignore` plugin lets you generate `.gitignore` files. What exact feature are you suggesting should be in mcdev?

**Comment by LaxWasHere** [comment]
It's not magically created.

**Comment by kinggoesgaming** [comment]
Thing is not everyone might want a VCS or might want something other than git
