### ISSUE TITLE
Add BukkitGradle support

### ISSUE THREAD

**Issue by OsipXD** [minecraft-dev/MinecraftDev#208]
Hello!
I'm writing [BukkitGradle](https://github.com/EndlessCodeGroup/BukkitGradle) (like a SpongeGradle but for Bukkit). What better way to add support of it to MinecraftDev?

If you give me direction, I think I can do it myself. I know Kotlin.

Thank you in advance.

P.S. Thanks for your hard work.

**Comment by DemonWav** [comment]
Thanks for the request, and BukkitGradle looks interesting.

However, currently BukkitGradle uses Yive's Mirror to download builds of Spigot. Unfortunately I can't condone that in MinecraftDev, as that violate's Spigot's licensing rules, so it's a no-go here. If you fix that (it would have to be totally removed, not just moved to a separate feature) then we can come back and consider how we would want to support it.

Another issue I see is there  doesn't appear to be support for CraftBukkit or Paper either. Maybe I just missed CraftBukkit, but I'm pretty sure there's no Paper support. As a Paper developer I am very interested in making sure it's fully supported. I like your plugin, and may even recommend people use it for their own projects, but as MinecraftDev provides full support for CraftBukkit, Spigot, and Paper each, so would BukkitGradle if it were to be added.

**Comment by osipxd** [comment]
Thanks for quick answer!
Yes, now possible use only Bukkit-API, but I have in plans to add ability to use Spigot, Paper APIs and CraftBukkit to use NMS and OBC.

About Yive's Mirror. I use it for getting spigot builds because I not found any alternatives. Do you know any legal repository that contains builded craftbukkit, spigot, paper cores? Of course I can use BuildTools from BukkitGradle, but it so slow.

P.S. Sorry for my bad english.

**Comment by JBYoshi** [comment]
There is no legal download of CraftBukkit. You have to use BuildTools.

**Comment by DemonWav** [comment]
Really your only option for a totally automatic system, which Spigot still considers to violate their ToS, but would be okay for my purposes, is to use my [Paperclip](https://github.com/PaperMC/Paperclip) system. But you would need to figure out distribution.

The easier option is to accept a path to a server jar they've acquired on their own, through BuildTools, Yive's, or whatever. But that removes the automated part of the system.

Paper already uses Paperclip for its distribution, so supporting it would be as simple as direct downloads. The others will be more difficult.

You can stick with using Yive's mirror if that's the easiest way to keep the whole system automated, but I can't add support for your Gradle plugin while it uses it.

**Comment by OsipXD** [comment]
Ok. Thanks for detailed answers. I'll try to fix rhis issue

**Comment by osipxd** [comment]
Hey. @DemonWav!

After more than year I finally removed license violations and added support of Paper.
Can you reopen this issue?

**Comment by DenWav** [comment]
No, this isn't a feature that I am willing to add into this plugin.

**Comment by osipxd** [comment]
That's a pity. Can you tell me reason? May be it will help me to improve BukkitGradle.

**Comment by DenWav** [comment]
The plugin looks nice, but it does not look like it provides significant benefit over the standard project layout for me to include it as the project template for Bukkit Gradle users. `plugin.yml` generation at build time isn't all that helpful, and could be actually quite annoying. Bukkit development just isn't that complex.

**Comment by osipxd** [comment]
Got it.
