### ISSUE TITLE
Let them begin - 2017.2 EPA gradle import issue

### ISSUE THREAD

**Issue by Meronat** [minecraft-dev/MinecraftDev#209]
This occurred when I created a new Sponge plugin project using the plugin with the Gradle setting.

Environment Information:

IntelliJ IDEA 2017.2 EAP
Build #IU-172.1909.2, built on May 2, 2017
IntelliJ IDEA EAP User
Expiration date: June 1, 2017
JRE: 1.8.0_152-release-837-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
Minecraft Development: 2017.2-0.6.3

![image](https://cloud.githubusercontent.com/assets/18372958/25767289/8f94433e-31bd-11e7-9fdf-a3b6beca6aa3.png)

**Comment by Meronat** [comment]
Not sure if it is related, but my project SDK was not defined either.

**Comment by DemonWav** [comment]
The fix will be in the next release, whenever that happens, hopefully not too long from now.
