### ISSUE TITLE
Suppress "Type may be weakened" inspection for event listener methods

### ISSUE THREAD

**Issue by JBYoshi** [minecraft-dev/MinecraftDev#210]
![image](https://cloud.githubusercontent.com/assets/12983479/25898677/c205e690-3552-11e7-9fbc-14978443461d.png)
(The same warning appears on `player`.)

See the test code on https://github.com/SpongePowered/SpongeCommon/issues/1344.

**Comment by DemonWav** [comment]
I wasn't even aware that was an inspection. Will do.

**Comment by RedNesto** [comment]
This inspection seem to be already suppressed on event listeners for a long time (perhaps thanks to using entrypoints?)
