### ISSUE TITLE
Look for main class before tagging a specific project

### ISSUE THREAD

**Issue by Katrix-** [minecraft-dev/MinecraftDev#217]
Currently developing a Sponge library, and MinecraftDev recognized my project as a Sponge project even though there is no main plugin class in the library. I'm a bit unsure if it's right to specify it as a sponge project in cases like those.

**Comment by JBYoshi** [comment]
It classifies that based on your dependency on SpongeAPI. Pretty much everything can be useful for a library that uses Sponge even if it doesn't provide a plugin itself. (And the check is also faster. :wink:)

**Comment by DemonWav** [comment]
Surely if you're writing code for Sponge (in a plugin or in a library to be used by a plugin) then it could still be considered a "Sponge project", no?
