### ISSUE TITLE
Add code generator for INBTSerializable in forge.

### ISSUE THREAD

**Issue by darkevilmac** [minecraft-dev/MinecraftDev#220]
It would be great if the plugin could just generate serialization code for fields by itself.

**Comment by gabizou** [comment]
@darkevilmac How would you consider fields that aren't `INBTSerializable`?

**Comment by darkevilmac** [comment]
Something similar to the toString method generator would make the most sense to me.

**Comment by DenWav** [comment]
This isn't something I'm interested in doing, however if someone wanted to implement this feature and PR it I would be willing to accept it.
