### ISSUE TITLE
Detect refrencing code with @SideOnly in Forge from the wrong side

### ISSUE THREAD

**Issue by Katrix** [minecraft-dev/MinecraftDev#28]
Would be nice if there was some sort of warning if you tried to reference code annotated `@SideOnly` from the wrong side in Forge, as such code would crash.

**Comment by DemonWav** [comment]
Thanks for the suggestion @Katrix- that sounds like a good idea. I'm not a Forge developer, however, so I honestly don't know what that means. I definitely can (and will) look it up to understand it, but it would be helpful to me if you could give me an example so I could get an idea of what you're talking about.

**Comment by JBYoshi** [comment]
@DemonWav Here's a short overview:

* In general, `@SideOnly` means that the code will only be present on the platform passed as a parameter (`CLIENT` for the client and integrated server, or `SERVER` for the dedicated server).
* Forge will refuse to load `@SideOnly` classes from the wrong side, throwing an exception.
* Forge deletes `@SideOnly` fields and methods from the wrong side.
* To get around `@SideOnly` limitations, Forge provides `@SidedProxy`, which is populated based on the side with either an instance of the `clientSide` or `serverSide` classes.

**Comment by Katrix-** [comment]
Basically the ´@SideOnly´ annotation specifies that something only exists on either the client or the server. Here is an example showing it in action

```java
public class SomeBlock extends Block {
	
	//Some fields that are present on the client side, the server side, and on both sides
	@SideOnly(Side.CLIENT)
	private final String clientSidedString = "clientSide";
	@SideOnly(Side.SERVER)
	private final String serverSidedString = "serverSide";
	
	private final String commonString = "common";

	public SomeBlock() {
		super(Material.CAKE);
	}
	
	//Some methods that are present on client side, server side and both sides
	//The Client and server method can still reference the common field, but not the other way around
	@SideOnly(Side.CLIENT)
	public String clientMethod() {
		return clientSidedString + commonString;
	}

	@SideOnly(Side.SERVER)
	public String serverMethod() {
		return serverSidedString + commonString;
	}

	public String commonMethod() {
		return commonString;
	}

	//This method will cause a crash as the field serverSidedString does not exist on the client side.
	@SideOnly(Side.CLIENT)
	public String crashMethod() {
		return serverSidedString;
	}
}
```

**Comment by loordgek** [comment]
you can also mark a class w/ @SideOnlyand that will delete the class for the wrong side

**Comment by loordgek** [comment]
can you do it also w/ @Optional.Method and @Optional.Interface/InterfaceList it will do the same thing but for mods
you give it a String modid and if the mod is not loaded that method/interface will be deleted

**Comment by DemonWav** [comment]
I see, thanks for the info. I'll see about implementing this after LiteLoader support is working.

**Comment by loordgek** [comment]
for more info read http://mcforge.readthedocs.io/en/latest/concepts/sides/

**Comment by DemonWav** [comment]
Currently only handling the cases where an annotated value is being used in an annotated method (so there's a lot more cases to check!) I've got this working so far.

![sideonlyerror](https://cloud.githubusercontent.com/assets/1332104/17075492/d90e66f6-505a-11e6-8f12-c52f7e304558.png)

**Comment by DemonWav** [comment]
I'm going to go ahead and release what I have so far. Test it out, try to find the edge cases where it breaks, and let me know if I got anything wrong or which cases I'm missing. If it causes problems you can always disable it in the Minecraft Settings page or disable them like any other inspection.

**Comment by Katrix-** [comment]
Haven't tried it too much yet although so far it looks great and has saved me from calling at least on client side method on the server. Thanks.

One thing that I guess we forgot to mention is the special case that is the proxy classes.
All mods define a server proxy and a client proxy in the somewhere in the mod(normally in the main mod class) with the `@SidedProxy` annotation. 

This annotation takes a String with the class path for the class for the client sided proxy and another string the the server sided proxy. These classes normally have some sort of inheritance (the most common patterns I have seen is either an interface that most classes implement, or the client proxy extending the server proxy and overriding methods).

The point here is that Forge will only ever load the class for the correct side, so even if they don't have the `@SideOnly` annotation, if you call a client sided method from the client side, it will be safe.

At the moment however such a call is marked as unsafe. (I hope all of this made sense, for more info see here: http://mcforge.readthedocs.io/en/latest/concepts/sides/#performing-side-specific-operations)

**Comment by Katrix-** [comment]
Here are the edge cases I've found so far. I'll update this if I find more.

Extending classes:
When you extend a class annotated with `@SideOnly`, it doesn't really make sense to annotate the class, at least from what I've heard (anyone here with more knowledge here?). So maybe allow sided methods if the parent class is sided as well?

Return types:
If a method returns an object that only exists on one side, it would make sense that the method also needs to be sided.

**Comment by DemonWav** [comment]
Good thoughts on both points, I'll add checks for both. I know about @SidedProxy, and I'm trying to come up with ways of handling it without duplicating lots of code. I'll update this if when I figure something out.

**Comment by Katrix-** [comment]
Here's a bug I found, If you have an array of a sided class, you don't get a warning.

**Comment by DemonWav** [comment]
I've got this working for `@SidedProxy` as well now.

**Comment by Katrix-** [comment]
Checked out stuff. Seems to not kick in immediately. Had to to fiddle with the annotation before it noticed anything. One thing that I did notice though is that this seems to be disallowed, even though it should be valid. `@SidedProxy` only tells forge to instantiate one or the other classes. AFAIK, both of them will exist on both sides, allowing you to do stuff like that.

```java
class CommonProxy {
	public void init(FMLInitializationEvent event) {
		<do stuff here>
	}
}

class ClientProxy extends CommonProxy {
	
	@Override
	public void init(FMLInitializationEvent event) {
		super.init(event)
		<do client stuff>
	}
}
```

**Comment by DemonWav** [comment]
Hmm, that _should_ be allowed, I'll have to check out why that's happening. It's unfortunately a really complex check, but I'm sure I'll get it nailed down at some point.

**Comment by gabizou** [comment]
![Image](https://puu.sh/rOw8b/de7e9d066a.png) A client side only mixing as declared by mixing is being highlighted. Granted, this requires that SideOnly checks that it's a mixin as well.

**Comment by Katrix-** [comment]
Here is a few other cases where a SideOnly should be inferred automatically. 

There exists a interface called `IGuiHandler` which has the methods `getClientGuiElement` and `getServerGuiElement` which delegates to the server and client side.

Recently Forge added a annotation called `@Mod.EventBusSubscriber`. This annotation will automatically register all static listeners in the class it's places on. This annotation can also take a `Side`, which in that case it will only register for that side. All static event listeners in a class with a sided `@EventBusSubscriber` should be also automatically be restricted to that side.

Lastly, and this is more of a question, I've encountered a few anomalies where a method isn't annotated with `SideOnly`, but where the method is still illegal because of the return type or the argument types. `getTextureOffset` in `ModelBase` is an example of this.

Something similar to this is what do to when it is crystal clear that client behavior should go in a method, but the method isn't sided. `ModelBase` is the only place I have encountered this so far. `ModelBase` has a method `render` which isn't sided. The problem comes from the fact that in the render method, what you are most definitively going to do is to call `render` on a `ModelRenderer` in your class. The only problem is that the `render` in `ModelRenderer` is sided.

**Comment by loordgek** [comment]
can you exclude the ClientProxy from this because the ClientProxy gets striped from a dedicated server

**Comment by Katrix-** [comment]
If you put the proxy in the `@SidedProxy` annotation it should behave mostly as expected. You might have to just rewrite the client part in the annotation though.

**Comment by loordgek** [comment]
that will work
but it is better to exclude it form the check

**Comment by loordgek** [comment]
can you exclude getClientGuiElement form IGuiHandler it is safe to call clientside stuff from there

**Comment by mezz** [comment]
I have a parent class and subclass both marked `@SideOnly(Side.CLIENT)`. 
When I call a super method from the child, it says my method must be annotated even though the entire class is already annotated.

Very useful so far, thanks for the plugin.

**Comment by mezz** [comment]
The issue seems to happen only when I'm calling the `super` version of the method.
![super-sided](https://cloud.githubusercontent.com/assets/916092/22875318/e2ccff1a-f17f-11e6-8acf-2b46839d70d6.png)

**Comment by mezz** [comment]
Found an issues that is easy to reproduce:

**Scenario:** 
An interface that is `@SideOnly(CLIENT)` is mistakenly applied to a class (`SlotForestry`) that should be available on both sides. 
**Expectation:** 
Anything using the class (`SlotForestry`) from server side should show a warning that it's client-only.
**Result:** 
No warnings

**Comment by Barteks2x** [comment]
Are there any more plans to improve it? There seems to be no way to make it usable except by marking most methods that reference sideonly code with another `@SideOnly`. So I ended up simply disabling this inspection, even when it could be a useful feature.

**Comment by DemonWav** [comment]
As a static analysis tool, it needs to know if a method is on one side or the other if it calls sided code. I am open to feedback if this isn't how you guys think it should behave, but this is the feeling I got initially.

As far as improvements planned, absolutely. There's still a lot of work to be done. I've just been working on some other things so I don't get burned out on this project. I plan on coming back to this soon. Some of the problems I need to solve with this set of inspections are very, very complex, however. So I can't provide any timeliness guarantees on anything. Keep in mind how very complicated the task is that the plugin is doing to statically analyze these things. :)

**Comment by mezz** [comment]
Most of my "unhandled" cases for this plugin are sections of code like this:
```java
if (someMethodReturningSide() == Side.CLIENT) {
    // client only methods called 
}
```
I don't know how the inspection stuff works, but IntelliJ seems to have an easy time finding this kind of pattern with its "Edit -> Find -> Search Structurally..." feature, so maybe something useful like that is exposed to you.

**Comment by DemonWav** [comment]
Yes that is certainly possible, and it's something I plan on working on. But I don't currently know how to utilize features like that for this inspection (or if I have to basically re-implement the logic for it from scratch - I doubt that).

**Comment by SquidDev** [comment]
I recently knocked up a [Java compiler plugin](https://github.com/SquidDev/forgelint) which did something similar to this (sorry, I hadn't realised you'd done it already). It has some support for #286 and #86, though the latter is currently very primitive (just supports `world.isRemote`).  I don't know if there's anything [in the code](https://github.com/SquidDev/forgelint/blob/master/src/main/java/org/squiddev/forgelint/sideonly/SideChecker.java) which is useful. I realise IntelliJ's APIs are very different to the one provided by Oracle, but hopefully there's something of use.

One issue neither checker seems to pick up on is initialising `@SideOnly` fields. When the field is stripped, the corresponding code in the constructor isn't removed and so will cause crashes. For instance, this should probably be marked as invalid:

```java
@SideOnly(Side.SERVER)
private int x = 23;
```

**Comment by DenWav** [comment]
Thanks, I'll need to add that check in. I'm currently redoing a lot of this whole inspection and it'll be disabled by default next release. Hopefully I'll get the time to work on it more again.
