### ISSUE TITLE
Search for event handling methods when passing instance to event bus

### ISSUE THREAD

**Issue by marvin-roesch** [minecraft-dev/MinecraftDev#32]
Note that I'm only going to talk from a Forge perspective here since I don't know any of the other systems in-depth.

It sometimes may happen that you register the wrong class to an event bus, making you wonder why your handlers are not called. To mitigate this issue, arguments for `EventBus.register` could be inspected, displaying a warning whenever a class is used which does not have any methods annotated with `@SubscribeEvent`. This obviously can't catch cases where the wrong class _with_ `@SubscribeEvent` methods is passed, but it would help a great deal either way!

**Comment by gabizou** [comment]
This can be handled in all three major platforms.
