### ISSUE TITLE
Suppress 'MethodMayBeStatic' on methods annoted with @Listener for Sponge (And other platform equivalents)

### ISSUE THREAD

**Issue by me4502** [minecraft-dev/MinecraftDev#43]
Currently IntelliJ will offer to make event listeners static, which prevents them from receiving the event.

**Comment by DemonWav** [comment]
This applies to all platforms, actually, I believe.

**Comment by me4502** [comment]
Probably, yeah

**Comment by kashike** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/5f234fdcf8f1d3841369e366f496f52142c78939

**Comment by DemonWav** [comment]
So does this just apply to `@SubscribeEvent`'s, or does it also apply to `@EventHandler`?

**Comment by MattBDev** [comment]
I believe this would also apply to `@EventHandler`

**Comment by DemonWav** [comment]
It appears IntelliJ has a bug which doesn't allow me to suppress inspections like ti seems I should be able to. I'll try and get more information on this soon.
