### ISSUE TITLE
Add Access Transformer shortcuts

### ISSUE THREAD

**Issue by ZephireNZ** [minecraft-dev/MinecraftDev#49]
My "wishlist":
- Clicking through a Access Transformer to it's location in the code - similar to how "Ctrl+Click" works on usages of functions and classes
- Generation of an Access Transformer from a class in the IDE. Could have fancy tick boxes for the various transformation options
- Maybe code suggestions for when a non-public method/variable is being used (and by showing an error in the IDE) despite it having a transformer such as when Gradle dependencies haven't been refreshed

**Comment by DemonWav** [comment]
Thanks for the suggestions. Those seem like reasonable features to add.

**Comment by ZephireNZ** [comment]
Oh, and another I thought of: similar to unused methods, highlight unused transformers as well as ones for stuff (such as old versions) that don't exist.

**Comment by Zidane** [comment]
Throwing in my support for this too. Big time saver.

**Comment by gabizou** [comment]
I'm curious how to figure out whether an unused transformer is necessary, because there can be ways that making something public is only resolvable if you scan the entire project for uses in the appropriate level.

**Comment by DemonWav** [comment]
Video showing some of the features that last commit added for access transformers: https://youtu.be/5pJMBYYWPeM

**Comment by DemonWav** [comment]
You think this is finished yet? What other features are missing for this?

**Comment by DemonWav** [comment]
These features are now fully implemented, the last access transformer feature planned is explained in #163.
