### ISSUE TITLE
Mixin support?

### ISSUE THREAD

**Issue by ryantheleach** [minecraft-dev/MinecraftDev#50]
Would it be possible to add support for 
- Navigating to targeted Mixin method/class
- generate an `@At` notation targetting annotation for the current cursor position?
- get the current method/class names in a mixin compatible format, e.g. `Lfoo/bar/Baz;func_1234_a(DDD)V`

---

- [ ] Java
- [ ] Scala
- [ ] Kotlin

**Comment by DemonWav** [comment]
Yep! We have [a branch](https://github.com/DemonWav/MinecraftDevIntelliJ/tree/feature/mixins) open for work in Mixins support. It hasn't been updated in a while, since I've been really busy, but I will have a lot more free time very soon to get back on and work on this stuff.

**Comment by loordgek** [comment]
is this usable by forge and the others ?
if so "platform: sponge" is a bit incorrect

**Comment by gabizou** [comment]
@loordgek Mixins are usable in three project types: forge, sponge, and liteloader. So yes, removing the sponge platform tag that @DemonWav did yesterday is valid.

**Comment by loordgek** [comment]
dint read it correctly my bad

**Comment by Aaron1011** [comment]
Some ideas for inspections:

* Error if the Mixin class itself is referenced anywhere
* Error if a shadow field/method is not found in the target class
* Error if any injections/redirects are found in a multi-target mixin (the `value` or `targets` arrays in `@Mixin` have more than one member).

**Comment by JBYoshi** [comment]
* Error if a mixin class is not referenced in any of the Mixin JSON files

**Comment by gabizou** [comment]
@JbYoshi, I feel like a problem that will arise is if mixons are being used in an environment other than headless in which case the json files will be difficult to evaluate. Likewise, I'd probably make it a warning instead of an errror so that it will not fail various checks and what not.

**Comment by kashike** [comment]
https://github.com/DemonWav/MinecraftDev/commit/d0a40799191c50ce80acf886b3f3dcff2c2f7528

**Comment by kinggoesgaming** [comment]
@gabizou `mixons` xD

**Comment by Deamon5550** [comment]
Additional feature requests:
While browsing minecraft sources:
- right click field > add access modifier
- right click method > add method overwrite
- right click method > add injection head/tail
- right click line > add general injection (good luck)

**Comment by DemonWav** [comment]
689e77d 88e3f59 98df069 and b2ba4db

**Comment by Minecrell** [comment]
@DemonWav Can we close this issue now? A lot has been added with previous commits / my PR and I suggest all new features/improvements should go into new issues instead so I can track them in the Mixin project: https://github.com/minecraft-dev/MinecraftDev/projects/3

**Comment by DemonWav** [comment]
Go for it.
