### ISSUE TITLE
Kotlin support?

### ISSUE THREAD

**Issue by yrsegal** [minecraft-dev/MinecraftDev#52]
None of the inspections and similar fire in kotlin, which is both a language that can be used for modding and supported directly through Jetbrains.

**Comment by DemonWav** [comment]
I recently started working with Kotlin for plugins and I noticed this as well. Hopefully it won't be too ridiculously difficult to add support for Kotlin. Worst-case scenario is each of the inspections will have to be re-written for Kotlin. I'm not sure if I'll do that if that's the case, because inevitably people will want Scala support as well. Maybe I'll just have Java, Kotlin, and Scala modules for the plugin, I don't know.

**Comment by yrsegal** [comment]
I feel like copying the inspections might end up being the only way to do it. Those three languages seem prudent, since kotlin is attached to intellij through jetbrains, and scala is packed in with forge.

**Comment by DemonWav** [comment]
I've created a new release channel for testing Kotlin and Scala support before I merge it into master. You can test it if you like by first updating the plugin to the most recent version, as it has a new feature that allows you to change the plugin's release channel. Once you've done that, you can open the action (Ctrl-Shift-A, or Cmd-Shift-A on Mac) `Configure Minecraft Development Plugin Updates`, or you can get to it from the settings page `File -> Settings -> Languages & Frameworks -> Minecraft Development -> Change plugin update channel`.

From there if you select the Kotlin and Scala channel and update the plugin you'll be able to test out the latest changes on the `feature/scotlin` branch.

**Comment by yrsegal** [comment]
When trying to use the Minecraft Development tab in L&F, I got this error:
```null
java.lang.NullPointerException
	at javax.swing.ImageIcon.<init>(ImageIcon.java:217)
	at com.demonwav.mcdev.MinecraftConfigurable.$$$setupUI$$$(MinecraftConfigurable.java)
	at com.demonwav.mcdev.MinecraftConfigurable.<init>(MinecraftConfigurable.java:17)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)```

the rest is a bunch of reflection stuff.

**Comment by DemonWav** [comment]
What's L&F? And I believe this is a remnant bug that will be fixed once I bring this branch back up to date with master.

**Comment by yrsegal** [comment]
Languages & Frameworks.

**Comment by DemonWav** [comment]
Oh, I see.

**Comment by DemonWav** [comment]
Closing this, this is moved to a milestone instead. https://github.com/minecraft-dev/MinecraftDev/milestone/2

**Comment by KitsuneDev** [comment]
Hey, sorry, but the project link seems to be broken (returning 404, and when I attempt to list projects, it shows as if no project exists). Is there any status on this, or anywhere to follow the progress/contribute? 
Thanks in advance :)
