### ISSUE TITLE
Choose parent module?

### ISSUE THREAD

**Issue by ryantheleach** [minecraft-dev/MinecraftDev#55]
I'm forever accidentally creating new modules while I have SpongeForge selected, which creates it as a sub-module of spongeforge, instead of yet another top level module.

If this matches other peoples workflows, it would be handy to have a step before naming the project in the wizard, that just confirms under what module that you wish to create, because I could then change it there, instead of cancelling the wizard, losing everything I've entered, de-selecting SpongeForge then recreating everything again.

**Comment by DemonWav** [comment]
@ryantheleach hmm, I'm not sure. It seems reasonable, I think, but I'll have to study that code again to see if that would actually be more difficult than it might seem (I haven't touched that bit of the code in a while). If anyone else could chime in their thoughts on this that would be great.

**Comment by ryantheleach** [comment]
if it's difficult don't worry about it, but gradle has an equivalent that lets you pick a gradle module (Yea it's probably completely different.) which is where I got the idea from.

![image](https://cloud.githubusercontent.com/assets/141554/18436676/bfb59b50-7938-11e6-8a75-d12907df9d3b.png)

**Comment by DemonWav** [comment]
Probably won't be that hard to do if I copy/paste the Gradle code ;)

**Comment by ryantheleach** [comment]
Hm, might be fixed one way or another, I just made a new forge mod with my existing SpongePlugin project selected, and it seemed to create as a top level module.

**Comment by ryantheleach** [comment]
I've retested this, unlike my comment on 6-Oct-2016 this is still making modules under SpongeForge.
