### ISSUE TITLE
Support for Minecraft json models

### ISSUE THREAD

**Issue by Katrix-** [minecraft-dev/MinecraftDev#56]
Here's an interesting idea.

Add some limited support for the minecraft json models. Mostly aimed at forge. I'm mostly thinking autocompletion to other models, and maybe some syntax highlighting here.

**Comment by loordgek** [comment]
can we get http://bdcraft.net/cubik integration ?
i dont know how and what. 
but maybe we can get a discussion going

**Comment by DemonWav** [comment]
Uhm, I'm not sure, I'll need some clarification on what you mean by integration. I could probably add a "jump to external editor" option in the context menu when you right click on the files like IntelliJ already does with images, but past that I'm not sure.

Please open a new issue for this so we can keep the discussions on these separate.

**Comment by Katrix** [comment]
Closing in favor of #266
