### ISSUE TITLE
Add Command

### ISSUE THREAD

**Issue by aikar** [minecraft-dev/MinecraftDev#62]
Option to add a command that creates a command executor

class package name should use JavaPlugin class as "base", and if base.commands package exists, default to that, else default to base

so if I have co.aikar.MyPlugin, and co.aikar.commands package, it would default to co.aikar.commands package, else co.aikar

on creation, add the setup commands to a "registerCommands()" method, and add the method to onEnable if it does not exists.

This should then encourage plugin devs to put any of their manual commands in that method.

If they don't like the auto placement, they could manually move it.

**Comment by kashike** [comment]
Singular package rather than plural - `com.example.command.*`.

**Comment by DemonWav** [comment]
Could just as well search for either.
Or just open a window with a class path, have default filled in, let the user change it.
