### ISSUE TITLE
Side issue should not be reported in forge when there is a check

### ISSUE THREAD

**Issue by liach** [minecraft-dev/MinecraftDev#86]
Example:
![image](https://cloud.githubusercontent.com/assets/7806504/19950928/01788f5a-a118-11e6-87b6-2b1a3083e34d.png)

Here is a `FMLCommonHandler.instance().getSide().isClient()` check to ensure error would not happen, just like how `optItem.isPresent()` check before `optItem.get()` call works. Hope you can do me a favor.

**Comment by DemonWav** [comment]
I'm working on this now, but it's rather difficult. This one might take a while to figure out.

**Comment by liach** [comment]
Now the issue is better since the side error is no longer marked as an error

**Comment by DenWav** [comment]
Probably because I disabled all of those inspections by default until I've finished the rewrite.
