### ISSUE TITLE
NullPointerException when editing Mixin Code

### ISSUE THREAD

**Issue by Faithcaio** [minecraft-dev/MinecraftDev#87]
http://pastie.org/private/soxb695wfqqbezofhbet1q

**Comment by DemonWav** [comment]
What version of the plugin are you using? This doesn't line up right with my code.

**Comment by Faithcaio** [comment]
It was Version: 2016.2-0.3.7

**Comment by Barteks2x** [comment]
I found the same issue, it seems to happen when the shadowed field (or method? tested only with field) doesn't exist.

**Comment by DemonWav** [comment]
I'm not totally sure that will fix this issue, so if it doesn't then reopen it.
