### ISSUE TITLE
Directly deploying code

### ISSUE THREAD

**Issue by Namnodorel** [minecraft-dev/MinecraftDev#88]
Maybe this is just undocumented, but I'd find it really, _really_ useful, if I could build/deploy my code with a single click. 

I'm active in Bukkit/Spigot development, and each time I made a small change to a plugin, I need to recompile the artifacts, go into the artifacts folder, copy + paste the file into my plugins folder, restart the server, rejoin, etc.

It is a really time-intensive, repititive and boring procedure, and I'm sure it look similar at modding. If these tasks could be automated, it would be a huuuuge deal for me and many many other minecraft developers. I know this is probably a lot of work, but [it will save time in the long run](https://xkcd.com/974/)!

No seriously. This is really needed.

**Comment by MiniDigger** [comment]
Idk about others, but I do that via my build script and intellij. I let intellij run the spigot jar and have intellij execute the build script before launch which copies the finished artifact into the plugins folder.
![http://i.minidigger.me/2016/11/idea_08_20-59-06.png](http://i.minidigger.me/2016/11/idea_08_20-59-06.png)
(I also have jrebel running which makes thing even faster but I think above does all you want)

**Comment by Namnodorel** [comment]
This is kinda what I need... But it still requires a special setup of the build process. What I had in mind would be similar to the Build Process in Android Studio - Press build, select a target and everything else runs on its own - no additional setup required.

**Comment by DemonWav** [comment]
That's certainly planned, but it's not terribly straightforward all the time to handle it. In preparation for adding the feature I created [BukkitStart](https://github.com/DemonWav/BukkitStart), so if you could give that a test and report any issues you find on it (to that repo, not this one) that would be helpful. Once I think it's stable enough I'll add BukkitStart as a default setup for new projects.

**Comment by Namnodorel** [comment]
Ok, I'm gonna look into it, as soon as I find some time

**Comment by DemonWav** [comment]
Due to the requirements of needing an external server jar, I don't think this is in the scope for this project to automatically handle. Since we can't run anything like `setupDecompWorkspace`, or download jars directly for Bukkit, I think it's safe to say this is something the developer will need to setup themselves after the project is created. As @MiniDigger pointed out, a jar run config is very simple to setup, so this shouldn't be much to ask.
