### ISSUE TITLE
Don't implement a Listener in the default main class

### ISSUE THREAD

**Issue by Namnodorel** [minecraft-dev/MinecraftDev#89]
Nobody who creates a plugin larger than a tutorial plugin will want to have the main class contain a Listener, that belongs to a specific class. So it is unnecessary to have the template implement a Listener, which will get removed most of the time by the user. 

More useful would be an option similar to #62 which allows the user to create a new Listener-Class from a template.

**Comment by DemonWav** [comment]
This is on steps to being removed, since the `Generate Listener` action auto-implements `Listener` if necessary. I just haven't gotten around to it.
