### ISSUE TITLE
A little documentation

### ISSUE THREAD

**Issue by ryantheleach** [minecraft-dev/MinecraftDev#9]
What new features to IntelliJ does this plugin bring?

**Comment by kashike** [comment]
https://plugins.jetbrains.com/plugin/8327 should give some information about this project. We'll work on documenting it better.

**Comment by DemonWav** [comment]
There's a site up now that has some information. It's not full of documentation yet, but It'll grow as we work on it. Site's here: https://minecraftdev.org/
