### ISSUE TITLE
Side is not detected from client/server only mixins

### ISSUE THREAD

**Issue by Barteks2x** [minecraft-dev/MinecraftDev#93]
Creating a client only mixin and referencing ClientOnly code from it is detected as referenced from unannotated method. While it's not annotated with `@SideOnly`, this method really exists only clientside.

**Comment by DemonWav** [comment]
Duplicate of #28.

**Comment by Barteks2x** [comment]
It doesn't look like duplicate.

My issue is that it thinks I'm calling from common side and shows me a warning when I don't want it.

**Comment by DemonWav** [comment]
@gabizou mentioned the issue in the thread. https://github.com/minecraft-dev/MinecraftDev/issues/28#issuecomment-254901716
