### ISSUE TITLE
Inspection "MCP Entity class missing World constructor" triggered at wrong places

### ISSUE THREAD

**Issue by Voidi** [minecraft-dev/MinecraftDev#94]
The Inspection "MCP Entity class missing World constructor" is triggered at generics which are bound to Entity.
![bildschirmfoto vom 2016-11-18 20-27-49](https://cloud.githubusercontent.com/assets/1231444/20443627/e2ca1e3a-adcd-11e6-994c-8c0a87170612.png)

**Comment by DemonWav** [comment]
Now this is hilarious. Thanks for the report!
