### ISSUE TITLE
Add checks for logical side

### ISSUE THREAD

**Issue by Katrix-** [minecraft-dev/MinecraftDev#97]
So, currently in Forge we have the `@SideOnly` check which helps catch calling code from the wrong physical side. However there is another concept of sides in minecraft, the logical sides. Whenever one runs a `world.isRemote` check this is what one is doing. 

Like calling code from the wrong physical side, calling code from the wrong logical side can also cause problems. This can range from ghost entities and desynchronization to exceptions. Unlike with the physical side, the problem one often faces with logical sides is that the server and the client has different information. For example, many data fields on entities are only stored on the logical server, and thus would be null on the logical client.

My proposal is to add something  to check for the logical side, similar to the check for physical side. Such a check would find both code accessing data on the wrong logical side, but also setting data on the wrong logical side. 

There are two big problems I can think of here however. 
The first is to find out what code can be accessed from which side. Unlike with the physical side, there are no annotations to help here. As with null fields, you just have to remember what fields can be accessed from which side. Some of these are easy to spot. For example, many fields in entities are initialized in constructors with more than the world argument. However the logical client will never call these constructors, just the constructor with the single world parameter.

The second problem is how to decide which logical side minecraft methods should be called from. There is the typical example of always checking if the world is remote before spawning an entity. That one it relatively easy. For a more complex method see `world.playSound` https://mcforge.readthedocs.io/en/latest/effects/sounds/#playing-sounds. If you pass in the client side player as the player argument, the method should be called on both sides. If the player is null, it only has an effect on the server side.

I am a bit unsure what would be a good way to solve the above problems. One approach is to use annotations similar to `@Nullable`. I also know that IntelliJ has some built in null interference. Maybe it's possible to use that in some way?

In the end, I don't know if it would be feasible to add such a feature as it's much less documented by stuff like annotations, but I still feel it would be a wonder if it was possible.

See here for more info on logical sides: https://mcforge.readthedocs.io/en/latest/concepts/sides/

**Comment by DemonWav** [comment]
I would love to support this, but you do bring up valid reasons for making it difficult. Annotations would be great, but I doubt we'll be able to get all of Forge to start using them. I don't know if it was PR'ed to Forge if it would actually be accepted.

I'm wondering if creating a database of methods and fields and their logical sides would be a feasible approach to this problem. It would require the help of people like you and other interested in such a feature, but it may be the simplest way of making sure we don't get any false-positives (as the method of checking the constructor sounds very false-positive friendly). Maybe a Google Sheet could be used for this, but I don't know what kind of success we would get from such an approach.

I've labeled this as input wanted, as I would be interested to see if there would be anyone who would be interested in helping document a beast like this.

**Comment by Katrix-** [comment]
Personally I think the best course of action might be some sort of combination. First of add some annotation that users can add both as documentation, and to help determine if the code can be called from there or not. For forge and minecraft internals some sort of database would be the easiest. I'd be more than happy to help with such a thing, seeing as there is a lot to be gained from it.

**Comment by DemonWav** [comment]
So would it be reasonable to have a Maven dependency to provide these annotations so devs can use them? I could setup a repo that could serve as the basis for the internal Forge database and the annotations.

**Comment by Katrix-** [comment]
I think that would be that best approach, so that people that don't use this won't see lots of red squiggly lines in their IDE.

For the annotation itself, here are my thoughts on it. You should be able to use it directly on either a field, a method or a constructor. On a field it means that the field should only ever be used from that side. On a method or constructor it means that the method should only ever be called from that side.

In my opinion to make stuff easier, the annotation should also be allowed to be applied to classes which means that the class should ever only be referenced from that side.

Also, for the Side enum, are you going to use another one, or reuse the forge one? Having to different side annotations can maybe be a bit tiresome, but I don't think you can pull in a dependency on them without also depending on forge (shouldn't matter too much though).

For the database, just insert `World.spawnEntityinWorld` and `Entity.setDead` for now. Those two should cover a large amount of stuff already.

**Comment by DenWav** [comment]
Based on feedback from @cpw this is really not a feasible task to accomplish in any meaningful way. Even the most well-designed solutions would still very likely be broken and otherwise unhelpful, as logical side checks are just too difficult to understand at compile time.

**Comment by cpw** [comment]
Yeah, this is an infeasible idea. You can't do effective code flow analysis at compile time to determine if World is a ClientWorld or ServerWorld, you can't figure out if your Network eventhandler is running in the Client Netty pool or the Server netty pool. All of these things will drastically affect whether you're on the client or server worlds. Sadly, the design of Java minecraft means this isn't going to be fixed any time soon.

My recommendation: you're always doing everything on the server threads. If you need to do something in the client, make it very obvious.
