### ISSUE TITLE
Add some support for packets

### ISSUE THREAD

**Issue by Katrix** [minecraft-dev/MinecraftDev#98]
Listing this as a separate issue as it has some non side specific stuff too.

So in Forge there is nice packet system called SimpleImpl. To use SimpleImpl you first create your own channel. Once you have that you can begin registering packets for it. When you register a packet, you give it a class that implements `IMessage` (holds the data, and is responsible for writing and reading the data), a class that implements `IMessageHandler` (handles the packet), and a `Side` where the packet should be handled. Both the packet class, and the handler class are required to have a constructor that takes no arguments.

The idea here is twofold.
1. Validate that the packet and handler class have empty constructors.
2. Don't mark the handler as invalid if it interacts with code for it's side.

AFAIK, the handler isn't really `@SideOnly`, it's just never touched on the wrong side, kind of like SidedProxy

More info here: https://mcforge.readthedocs.io/en/latest/networking/simpleimpl/

**Comment by Barteks2x** [comment]
Would be also nice to not mark the empty constructor as unused, but i'm not sure if a plugin can do that. Since there is no annotation on that class/constructor, I can't tell idea to ignore unused constructor when that annotation is used.

**Comment by DemonWav** [comment]
The plugin should be able to do that @Barteks2x, but when it comes to suppressing warnings I believe there is a bug in IntelliJ which prevents plugins from doing it, even though they are supposed to be able to. I'll have to investigate that more.

**Comment by DemonWav** [comment]
Just to update this, we now have a way to suppress warnings, so this should be something that I can easily fix.
